// Auto-generated by package_frontend.ts - ADOBE QUALITY ENHANCED
export const registry = { tiers: {
  "1": [
    {
      "id": "create-me-a-better-version-of-a-pokeball (1)",
      "path": "assets/create-me-a-better-version-of-a-pokeball (1).png",
      "type": "png",
      "name": "create-me-a-better-version-of-a-pokeball (1).png"
    },
    {
      "id": "create-me-a-better-version-of-a-pokeball (2)",
      "path": "assets/create-me-a-better-version-of-a-pokeball (2).png",
      "type": "png",
      "name": "create-me-a-better-version-of-a-pokeball (2).png"
    },
    {
      "id": "create-me-a-better-version-of-a-pokeball",
      "path": "assets/create-me-a-better-version-of-a-pokeball.png",
      "type": "png",
      "name": "create-me-a-better-version-of-a-pokeball.png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-bonus- (1)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-bonus- (1).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-bonus- (1).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-bonus- (2)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-bonus- (2).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-bonus- (2).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-bonus- (3)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-bonus- (3).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-bonus- (3).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-bonus-",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-bonus-.png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-bonus-.png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-multip (1)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-multip (1).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-multip (1).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-multip",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-multip.png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-multip.png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-sprite (1)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-sprite (1).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-sprite (1).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-sprite (2)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-sprite (2).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-sprite (2).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-sprite (3)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-sprite (3).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-sprite (3).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-sprite",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-sprite.png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-sprite.png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-symbol (1)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-symbol (1).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-symbol (1).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-symbol (2)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-symbol (2).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-symbol (2).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-symbol (3)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-symbol (3).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-symbol (3).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-symbol (4)",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-symbol (4).png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-symbol (4).png"
    },
    {
      "id": "create-me-a-better-version-of-pokemon-slots-symbol",
      "path": "assets/create-me-a-better-version-of-pokemon-slots-symbol.png",
      "type": "png",
      "name": "create-me-a-better-version-of-pokemon-slots-symbol.png"
    }
  ],
  "2": [],
  "3": [],
  "4": [],
  "5": []
}, total: 18 };
export const adobeSVG = {
  "pokeball": "<svg viewBox=\"0 0 100 100\"><defs><radialGradient id=\"pb-top\" cx=\"0.3\" cy=\"0.3\"><stop offset=\"0%\" stop-color=\"#ff6b6b\"/><stop offset=\"40%\" stop-color=\"#e74c3c\"/><stop offset=\"100%\" stop-color=\"#c0392b\"/></radialGradient><radialGradient id=\"pb-bottom\" cx=\"0.3\" cy=\"0.7\"><stop offset=\"0%\" stop-color=\"#ffffff\"/><stop offset=\"40%\" stop-color=\"#f8f9fa\"/><stop offset=\"100%\" stop-color=\"#e9ecef\"/></radialGradient><radialGradient id=\"pb-center\" cx=\"0.5\" cy=\"0.5\"><stop offset=\"0%\" stop-color=\"#ffffff\"/><stop offset=\"70%\" stop-color=\"#6c757d\"/><stop offset=\"100%\" stop-color=\"#343a40\"/></radialGradient><filter id=\"shadow\" x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\"><feDropShadow dx=\"2\" dy=\"4\" stdDeviation=\"3\" flood-color=\"#000\" flood-opacity=\"0.3\"/></filter></defs><circle cx=\"50\" cy=\"50\" r=\"45\" fill=\"url(#pb-top)\" filter=\"url(#shadow)\"/><path d=\"M 5 50 A 45 45 0 0 1 95 50 Z\" fill=\"url(#pb-bottom)\"/><rect x=\"5\" y=\"47\" width=\"90\" height=\"6\" fill=\"#2c3e50\"/><circle cx=\"50\" cy=\"50\" r=\"15\" fill=\"url(#pb-center)\" stroke=\"#2c3e50\" stroke-width=\"2\"/><circle cx=\"50\" cy=\"50\" r=\"8\" fill=\"none\" stroke=\"#495057\" stroke-width=\"2\"/></svg>",
  "pikachu": "<svg viewBox=\"0 0 100 100\"><defs><radialGradient id=\"pika-body\" cx=\"0.3\" cy=\"0.3\"><stop offset=\"0%\" stop-color=\"#ffd43b\"/><stop offset=\"60%\" stop-color=\"#f39c12\"/><stop offset=\"100%\" stop-color=\"#d68910\"/></radialGradient><filter id=\"electric-glow\"><feGaussianBlur stdDeviation=\"3\"/><feColorMatrix values=\"1 1 0 0 0  1 1 0 0 0  0 0 1 0 0  0 0 0 1 0\"/></filter></defs><ellipse cx=\"50\" cy=\"60\" rx=\"25\" ry=\"30\" fill=\"url(#pika-body)\"/><circle cx=\"35\" cy=\"40\" r=\"8\" fill=\"#2c3e50\"/><circle cx=\"65\" cy=\"40\" r=\"8\" fill=\"#2c3e50\"/><path d=\"M 30 20 Q 25 10 20 15 Q 15 25 25 30\" fill=\"#ffd43b\"/><path d=\"M 70 20 Q 75 10 80 15 Q 85 25 75 30\" fill=\"#ffd43b\"/><ellipse cx=\"40\" cy=\"50\" rx=\"3\" ry=\"2\" fill=\"#e74c3c\"/><ellipse cx=\"60\" cy=\"50\" rx=\"3\" ry=\"2\" fill=\"#e74c3c\"/><path d=\"M 45 60 Q 50 65 55 60\" stroke=\"#2c3e50\" stroke-width=\"2\" fill=\"none\"/><circle cx=\"50\" cy=\"50\" r=\"40\" fill=\"none\" stroke=\"#f1c40f\" stroke-width=\"1\" opacity=\"0.3\" filter=\"url(#electric-glow)\"/></svg>",
  "charizard": "<svg viewBox=\"0 0 100 100\"><defs><radialGradient id=\"char-body\" cx=\"0.3\" cy=\"0.3\"><stop offset=\"0%\" stop-color=\"#ff7675\"/><stop offset=\"60%\" stop-color=\"#e17055\"/><stop offset=\"100%\" stop-color=\"#d63031\"/></radialGradient><radialGradient id=\"flame\" cx=\"0.5\" cy=\"0.8\"><stop offset=\"0%\" stop-color=\"#fdcb6e\"/><stop offset=\"50%\" stop-color=\"#e17055\"/><stop offset=\"100%\" stop-color=\"#d63031\"/></radialGradient></defs><ellipse cx=\"50\" cy=\"55\" rx=\"30\" ry=\"35\" fill=\"url(#char-body)\"/><ellipse cx=\"30\" cy=\"30\" rx=\"15\" ry=\"8\" fill=\"url(#char-body)\"/><ellipse cx=\"70\" cy=\"30\" rx=\"15\" ry=\"8\" fill=\"url(#char-body)\"/><circle cx=\"40\" cy=\"45\" r=\"6\" fill=\"#2c3e50\"/><circle cx=\"60\" cy=\"45\" r=\"6\" fill=\"#2c3e50\"/><path d=\"M 45 55 L 50 65 L 55 55\" fill=\"#2c3e50\"/><path d=\"M 40 25 Q 30 15 25 20 Q 20 30 30 35\" fill=\"url(#flame)\"/><path d=\"M 60 25 Q 70 15 75 20 Q 80 30 70 35\" fill=\"url(#flame)\"/></svg>",
  "squirtle": "<svg viewBox=\"0 0 100 100\"><defs><radialGradient id=\"squir-body\" cx=\"0.3\" cy=\"0.3\"><stop offset=\"0%\" stop-color=\"#74b9ff\"/><stop offset=\"60%\" stop-color=\"#0984e3\"/><stop offset=\"100%\" stop-color=\"#2d3436\"/></radialGradient><radialGradient id=\"shell\" cx=\"0.5\" cy=\"0.3\"><stop offset=\"0%\" stop-color=\"#a29bfe\"/><stop offset=\"60%\" stop-color=\"#6c5ce7\"/><stop offset=\"100%\" stop-color=\"#2d3436\"/></radialGradient></defs><ellipse cx=\"50\" cy=\"65\" rx=\"20\" ry=\"25\" fill=\"url(#squir-body)\"/><ellipse cx=\"50\" cy=\"40\" rx=\"35\" ry=\"30\" fill=\"url(#shell)\"/><circle cx=\"40\" cy=\"35\" r=\"6\" fill=\"#2c3e50\"/><circle cx=\"60\" cy=\"35\" r=\"6\" fill=\"#2c3e50\"/><path d=\"M 45 45 Q 50 50 55 45\" stroke=\"#2c3e50\" stroke-width=\"2\" fill=\"none\"/><ellipse cx=\"30\" cy=\"60\" rx=\"8\" ry=\"12\" fill=\"url(#squir-body)\"/><ellipse cx=\"70\" cy=\"60\" rx=\"8\" ry=\"12\" fill=\"url(#squir-body)\"/></svg>"
};
export function byTier(t){ return (registry.tiers[String(t)]||registry.tiers[t]||[]); }
export function allAssets(){ return ([]).concat(registry.tiers[1]||[], registry.tiers[2]||[], registry.tiers[3]||[], registry.tiers[4]||[], registry.tiers[5]||[]); }
export function randomSymbol(t){ const arr = t? byTier(t): allAssets(); if (!arr.length) return null; return arr[Math.floor(Math.random()*arr.length)]; }
export function getAdobeSVG(name){ return adobeSVG[name] || null; }
export function createSVGElement(name, size=64){ const svg = getAdobeSVG(name); if (!svg) return null; const div = document.createElement('div'); div.innerHTML = svg; const el = div.firstElementChild; if (el) { el.style.width = size+'px'; el.style.height = size+'px'; } return el; }
// Enhanced: Use SVG if available, fallback to PNG
export function popSymbol(symbolIdOrPath, ms=600) {
  const o = document.getElementById('overlay');
  if (!o) return;
  let el = null;
  // Try SVG first
  if (adobeSVG && adobeSVG[symbolIdOrPath]) {
    el = document.createElement('div');
    el.innerHTML = adobeSVG[symbolIdOrPath];
    el = el.firstElementChild;
    el.classList.add('pop');
    el.style.position = 'absolute';
    el.style.left = '50%';
    el.style.top = '50%';
    el.style.transform = 'translate(-50%, -50%)';
    el.style.maxWidth = '40%';
    el.style.maxHeight = '70%';
  } else {
    // Fallback to PNG
    el = document.createElement('img');
    el.src = symbolIdOrPath;
    el.alt = 'symbol';
    el.className = 'pop';
    el.style.position = 'absolute';
    el.style.left = '50%';
    el.style.top = '50%';
    el.style.transform = 'translate(-50%, -50%)';
    el.style.maxWidth = '40%';
    el.style.maxHeight = '70%';
  }
  o.appendChild(el);
  setTimeout(() => el.remove(), ms);
}

export function popSymbolAt(symbolIdOrPath, xPct, yPct, ms=600) {
  const o = document.getElementById('overlay');
  if (!o) return;
  let el = null;
  if (adobeSVG && adobeSVG[symbolIdOrPath]) {
    el = document.createElement('div');
    el.innerHTML = adobeSVG[symbolIdOrPath];
    el = el.firstElementChild;
    el.classList.add('pop');
    el.style.position = 'absolute';
    el.style.left = (xPct * 100) + '%';
    el.style.top = (yPct * 100) + '%';
    el.style.transform = 'translate(-50%, -50%)';
    el.style.maxWidth = '40%';
    el.style.maxHeight = '70%';
  } else {
    el = document.createElement('img');
    el.src = symbolIdOrPath;
    el.alt = 'symbol';
    el.className = 'pop';
    el.style.position = 'absolute';
    el.style.left = (xPct * 100) + '%';
    el.style.top = (yPct * 100) + '%';
    el.style.transform = 'translate(-50%, -50%)';
    el.style.maxWidth = '40%';
    el.style.maxHeight = '70%';
  }
  o.appendChild(el);
  setTimeout(() => el.remove(), ms);
}
// Heuristic mapping from engine symbol ids to available assets
export const engineTierMap = { pikachu:1, charizard:2, squirtle:3, bulbasaur:4, jigglypuff:5, eevee:5, mew:5, snorlax:5 };
const aliasMap = {
  "pikachu": [
    "pikachu"
  ],
  "charizard": [
    "charizard",
    "charmander"
  ],
  "squirtle": [
    "squirtle"
  ],
  "bulbasaur": [
    "bulbasaur"
  ],
  "jigglypuff": [
    "jigglypuff"
  ],
  "eevee": [
    "eevee",
    "evee"
  ],
  "mew": [
    "mew"
  ],
  "snorlax": [
    "snorlax"
  ],
  "freespins": [
    "free spins",
    "freespins",
    "free-spins",
    "scatter",
    "free"
  ],
  "wild": [
    "multi",
    "multiplier",
    "x"
  ],
  "pokeball": [
    "pokeball",
    "poke ball"
  ],
  "masterball": [
    "master ball",
    "masterball"
  ]
};
function extPriority(ext){ switch(String(ext||'').toLowerCase()){ case 'png': return 5; case 'webp': return 4; case 'jpg': case 'jpeg': return 3; case 'svg': return 2; default: return 1; } }
function pickBest(candidates){ if (!candidates || !candidates.length) return null; let best = candidates[0]; let bestScore = extPriority(best.type); for (const c of candidates){ const s = extPriority(c.type); if (s>bestScore){ best = c; bestScore = s; } } return best; }
function findAssetsByExactId(id){ const low = String(id||'').toLowerCase(); return allAssets().filter(a=> String(a.id||'').toLowerCase() === low); }
function findAssetsByLooseMatch(id){ const low = String(id||'').toLowerCase(); return allAssets().filter(a=> String(a.id||'').toLowerCase().includes(low)); }
export function pathFor(symbolId){
  const raw = String(symbolId||'');
  const id = raw.toLowerCase();
  // 1) exact id match
  let found = pickBest(findAssetsByExactId(id));
  if (found) return found.path;
  // 2) loose variants of the raw id (handles underscores/spaces and t2 vs T2)
  const variants = [
    id,
    id.replace(/_/g,' '),
    id.replace(/_/g,''),
    id.replace(/_/g,' ').replace(/ts*([1-5])$/,'t$1'),
    id.replace(/_/g,'').replace(/ts*([1-5])$/,'t$1'),
  ];
  for (const v of variants){ const f = pickBest(findAssetsByLooseMatch(v)); if (f) return f.path; }
  // 3) alias strings (for specials and common renames)
  const aliases = aliasMap[id];
  if (aliases){ for (const alt of aliases){ const f = pickBest(findAssetsByLooseMatch(alt)); if (f) return f.path; } }
  // 4) engine tier fallback t1..t5 buckets
  const t = engineTierMap[id]; if (t){ const f = pickBest(findAssetsByExactId('t'+String(t))); if (f) return f.path; }
  for (let k=1;k<=5;k++){ const f = pickBest(findAssetsByExactId('t'+String(k))); if (f) return f.path; }
  // 5) last resort: any asset
  const any = pickBest(allAssets()); return any? any.path : '';
}
export function spriteFor(symbolId){ const p = pathFor(symbolId); if (!p) return null; return { id: symbolId, path: p }; }
